version: '3.5'

services:
  mysql-8:
    container_name: mysql-db-8
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paracasa-db
      MYSQL_USER: paracasa
      MYSQL_PASSWORD: paracasa
    networks:
      - backend
    volumes:
      - "data-db-mysql:/var/lib/mysql"
  paracasa-service:
    build: .
    ports:
      - "8080:8080"
    command: java -jar -Dspring.profiles.active=docker target/paracasa.jar
    networks:
      - backend
    depends_on:
      - mysql-8

volumes:
  data-db-mysql:
networks:
  backend: