version: '3.5'

services:
  mysql-8:
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paracasa-db
      MYSQL_USER: paracasa
      MYSQL_PASSWORD: paracasa
    networks:
      - backend
    volumes:
      - "data-db-mysql:/var/lib/mysql"
  paracasa-service:
    build: .
    ports:
      - "8080:8080"
    command: java -jar -Dspring.profiles.active=docker target/paracasa.jar
    networks:
      - backend

    depends_on:
      - mysql-8
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-8:3306/paracasa-db?useSSL=false&allowPublicKeyRetrieval=True&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: paracasa
      SPRING_DATASOURCE_PASSWORD: paracasa

volumes:
  data-db-mysql:

networks:
  backend:
