#server.servlet.context-path=/backendteam

spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          batch_size: 50
          
  datasource:
    url: jdbc:mysql://localhost/prueba?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 
